export default {
    common: {
        defaultLanguage: 'English',
        close: 'Close',
        noText: 'No text',
        noData: 'No Data',
        cancel: 'Cancel',
        confirm: 'Confirm',
        haveAnAcc: 'Do you have an account? ',
        login: 'Login',
        stockMarket: 'Stock Market',
        open: 'Open',
        high: 'High',
        low: 'Low',
        closeStock: 'Close',
        volume: 'Traded Volume',
        date: 'Date',
        symbol: 'Symbol',
        search: 'Search',
        notFound: 'Not found',
        ok: 'OK',
        setting: 'Setting',
        update: 'Update',
        newPass: 'Set new password',
    },
    forgotPass: {
        title: 'Forgot Password',
        subTitle: 'Please enter your email we will resend you a verify code.',
        next: 'Next',
    },
    permissions: {
        camera: 'Stock Market need the camera permission',
        photo: 'Stock Market need access library permission',
    },
    stock: {
        highestVolume: 'Highest trading volume today',
        stockToday: 'Stock Market Data',
    },
    news: {
        comment: 'Comment',
        addNews: 'Post something...',
        hide: 'This post has been hidden',
        hideComment: 'Comment was hidden',
    },
    addNews: {
        title: 'Title',
        content: 'Content',
        takePictureHeader: 'Take a photo',
        takePicture: 'Camera',
        chooseFromAlbum: 'Library',
        upload: 'Post',
        noComment: 'No comments yet',
    },
    watchlist: {
        noData: 'You do not have any symbol in watch list',
        title: 'Watch List',
    },
    courseScreen: {
        all: 'All',
        noCourse: 'No courses yet',
        author: 'Author {{ value }}',
        createdAt: 'Created at {{ value }}',
    },
    firstScreen: {
        brand: 'STOCK MARKET',
        description: 'Feel the new \n experience of our product',
        gettingStarted: 'Getting Started',
    },
    modalInput: {
        title: 'Hello',
        close: 'Close',
        button: 'displayModal1',
    },
    tab: {
        home: 'Home',
        news: 'News',
        market: 'Watchlist',
        setting: 'Settings',
        course: 'Course',
    },
    alert: {
        button: {
            no: 'No',
            yes: 'Yes',
        },
        addSuccess: 'Add success!',
        updateSuccess: 'Update success',
        warning: 'Warning',
    },
    loginScreen: {
        buttonLogin: 'Login',
        labelEmail: 'Email',
        labelPassword: 'Password',
        forgotPassword: 'Forgot password?',
        dontHaveAnAccount: 'You do not have an account? ',
        register: 'Register',
    },
    registerScreen: {
        title: 'Register',
        username: 'Username',
        phone: 'Phone',
        email: 'Email',
        password: 'Password',
        confirm_password: 'Confirm password',
        placeholder_username: 'Tuan Pham Ngoc',
        haveAnAccount: 'Do you have an account? ',
        login: 'Login',
        photo: 'Album',
        camera: 'Take a photo',
        selectPhoto: 'Camera',
        chooseImage: 'Library',
    },
    validateMessage: {
        nameRequired: 'At least 6 character of username',
        signIn: 'Password is incorrect!',
        infoInvalid: 'Info invalid!',
        notCompleted: 'You have not entered the information.',
        emailNotRegister: 'Please enter your email!',
        validatePassword: 'At least 6 character of password!',
        minLength: 'At least 6 character of password!',
        emailInvalid: 'Email is not in the correct format!',
        passwordLength: 'At least 6 character of password!',
        confirmPasswordLength: 'The password and confirmation password do not match.',
        passwordNotMatch: 'The password and confirmation password do not match.',
        emailEmpty: 'Please enter your email!',
        messageLength: 'Do not enter more than 1000 characters.',
        success: 'Register success!',
        titleRequired: 'Title is required!',
        contentRequired: 'Content is required!',
        phoneInvalid: 'Phone invalid',
        require: 'Please enter the information',
        notMatchPassword: 'The password and confirmation password do not match.',
    },
    sendOTP: {
        title: 'Email Verification',
        subTitle: 'Please check your email.',
        success: 'A new verification code has been sent.',
        invalidOTP: 'The authorization code is incorrect.',
        resend: 'Resend',
        buttonNext: 'Next',
    },
    input: {
        errorComponent: 'You need wrap input by Form Provider or passing "form = useForm( ... )" into input component',
    },
    settings: {
        logout: 'Logout',
        profile: 'Update Profile',
        english: 'English',
        changeLang: 'Change language',
        selectLang: 'Language selection',
        multiLangSupported: 'Multi language supported',
        vietnamese: 'Vietnamese',
        deleteAccount: 'Delete account',
        delete: 'Confirm',
        deleteConfirm: 'Do you want to delete your account?',
        changePass: 'Change password',
        aboutUs: 'About Us',
        privacyPolicy: 'Privacy policy',
        termsOfService: 'Terms of service',
    },
    updateProfile: {
        update: 'Update',
        reset: 'Reset',
    },
    confirmModal: {
        addToWatchlist: 'Add stock to watch list',
        contentTextAdd: 'Easy to follow your watch list',
        remove: 'Remove stock from watch list',
        delete: 'Are you sure to delete your post',
    },
    changePass: {
        oldPass: 'Old password',
        newPass: 'New password',
        confirmPass: 'Confirm password',
    },
    toastMessage: {
        addSuccess: 'Add symbol to watch list successfully',
        removeSuccess: 'Remove symbol from watch list successfully',
        deleteSuccess: 'Delete successfully',
        addPostSuccess: 'Post successfully',
        updatePostSuccess: 'Update post successfully',
        nothingToComment: 'Please write your comment',
        commentSuccess: 'Comment successfully!',
        updateProfileSuccess: 'Update profile successfully',
        changeSuccess: 'Change password successfully!',
    },
};
