export default {
    common: {
        defaultLanguage: 'English',
        close: 'Close',
        noText: 'No text',
        noData: 'No Data',
        cancel: 'Cancel',
        confirm: 'Confirm',
        haveAnAcc: 'Do you have an account? ',
        login: 'Login',
        stockMarket: 'Stock Market',
    },
    firstScreen: {
        brand: 'STOCK MARKET',
        description: 'Feel the new \n experience of our product',
        gettingStarted: 'Getting Started',
    },
    modalInput: {
        title: 'Hello',
        close: 'Close',
        button: 'displayModal1',
    },
    tab: {
        home: 'Home',
        news: 'News',
        market: 'Watchlist',
        setting: 'Settings',
    },
    alert: {
        button: {
            no: 'No',
            yes: 'Yes',
        },
        addSuccess: 'Add success!',
        updateSuccess: 'Update success',
        warning: 'Warning',
        complete: 'テストを完了してもよろしいですか？',
        score: '点数',
    },
    noData: {
        noDataList: 'Không có dữ liệu',
        noDataRateList: '評価がまだありません',
        noDataHoliday: 'なし',
    },
    loginScreen: {
        buttonLogin: 'Login',
        labelEmail: 'Email',
        labelPassword: 'Password',
        forgotPassword: 'Forgot password?',
        dontHaveAnAccount: 'You do not have an account? ',
        register: 'Register',
    },
    registerScreen: {
        title: 'Register',
        username: 'Username',
        phone: 'Phone',
        email: 'Email',
        password: 'Password',
        confirm_password: 'Confirm password',
        placeholder_username: 'Tuan Pham Ngoc',
        haveAnAccount: 'Do you have an account? ',
        login: 'Login',
    },
    validateMessage: {
        nameRequired: 'Username is required!',
        signIn: 'Password is incorrect!',
        infoInvalid: 'Info invalid!',
        notCompleted: 'You have not entered the information.',
        emailNotRegister: 'Please enter your email!',
        validatePassword: 'At least 6 character of password!',
        minLength: 'At least 6 character of password!',
        emailInvalid: 'Email is not in the correct format!',
        passwordLength: 'At least 6 character of password!',
        confirmPasswordLength: 'The password and confirmation password do not match.',
        passwordNotMatch: 'The password and confirmation password do not match.',
        emailEmpty: 'Please enter your email!',
        messageLength: 'Do not enter more than 1000 characters.',
        success: 'Register success!',
        titleRequired: 'Title is required!',
        contentRequired: 'Content is required!',
        phoneInvalid: 'Phone invalid',
        require: 'Please enter the information',
        notMatchPassword: 'The password and confirmation password do not match.',
    },
    sendOTPMessage: {
        success: 'A new verification code has been sent.',
        invalidOTP: 'The authorization code is incorrect.',
    },
    homeListScreen: {
        title: 'メッセージ',
        tab1: '全て',
        tab2: '未読',
        tab3: '既読',
    },
    testScreen: {
        loadingTest: '読み込み中...',
        notification: 'スタートボタンをクリックしてテストを受けてください！',
        startButton: 'Start',
        exercise: '問題 ',
        titleHeader: 'Vocabulary - Kanji - Grammar',
        completeButton: 'Complete',
        topic: '言語知識 (文字 - 単語 - 文法)',
        exercise1: '問題１　＿＿＿のことばの読み方として最もよいものを、１・２・３・４から一つえらびなさい。',
    },
    homeScreen: {
        model: 'モデル',
        detailScreen: '詳細画面',
        dataScreen: 'データ画面',
        userListScreen: 'メッセージ管理画面',
        triggerLoading: '読み込み中',
        testScreen: '試験を受ける',
        batteryScreen: '電池画面',
        quickTest: '速いテストを受ける',
    },
    accountView: {
        name: 'name',
        phone: 'phone',
        email: 'email',
        password: 'password',
        confirmPassword: 'confirmPassword',
    },
    sendOTP: {
        title: 'Mã xác nhận',
        titleForgotPassword: 'Quên mật khẩu',
        sendForgotPassword: 'Xác nhận',
        backButton: 'Trở về',
        descriptionNext:
            '入力したメールアドレスに通知メールを送信しました。\n 認証コードを入力し、「次へ」ボタンを押してください。有効期限は24時間です。',
        descriptionConfirm:
            '入力したメールアドレスに通知メールを送信しました。\n 認証コードを入力し、「確認」ボタンを押してください。有効期限は24時間です。',
        description:
            '入力したメールアドレスに通知メールを送信しました。認証コードを入力し、「登録」ボタンを押してください。有効期限は24時間です。',
        resend: '再送信',
        buttonSend: '登録',
        buttonNext: '次へ',
    },
    errorMessage: {
        emailExisted: 'Địa chỉ email đã tồn tại',
    },
    sendEmail: {
        title: 'Quên mật khẩu',
        sendButtonTitle: 'Tiếp theo',
    },
    picker: {
        pickItem: 'Vui lòng chọn thư mục',
    },
    input: {
        errorComponent: 'You need wrap input by Form Provider or passing "form = useForm( ... )" into input component',
    },
    addMessengerScreen: {
        buttonAdd: 'Add messenger',
        labelTitle: 'Title',
        labelContent: 'Content',
        placeholderTitle: 'your title',
        placeholderContent: 'your content',
    },
    updateMessengerScreen: {
        buttonUpdate: 'Update',
        labelTitle: 'Title',
        labelContent: 'Content',
        labelStatus: 'Status',
    },
    settings: {
        logout: 'Logout',
        profile: 'Update Profile',
        english: 'English',
        changeLang: 'Change language',
        selectLang: 'Language selection',
        multiLangSupported: 'Multi language supported',
        vietnamese: 'Vietnamese',
        deleteAccount: 'Delete account',
        delete: 'Confirm',
        deleteConfirm: 'Do you want to delete your account?',
    },
    updateProfile: {
        update: 'Update',
        reset: 'Reset',
    },
};
