export default {
    common: {
        defaultLanguage: 'English',
        close: 'Close',
        noText: 'No text',
        noData: 'No Data',
        cancel: 'Cancel',
        confirm: 'Confirm',
        haveAnAcc: 'Do you have an account? ',
        login: 'Login',
        stockMarket: 'Stock Market',
        open: 'Open',
        high: 'High',
        low: 'Low',
        closeStock: 'Close',
        volume: 'Traded Volume',
        date: 'Date',
        symbol: 'Symbol',
        search: 'Search',
        notFound: 'Not found',
    },
    stock: {
        highestVolume: 'Highest trading volume today',
        stockToday: 'Stock Market Data',
    },
    firstScreen: {
        brand: 'STOCK MARKET',
        description: 'Feel the new \n experience of our product',
        gettingStarted: 'Getting Started',
    },
    modalInput: {
        title: 'Hello',
        close: 'Close',
        button: 'displayModal1',
    },
    confirmModal: {
        addToWatchlist: 'Add stock to watch list',
        contentTextAdd: 'Easy to follow your watch list',
        removeFromWatchList: 'Remove stock from watch list',
    },
    tab: {
        home: 'Home',
        news: 'News',
        market: 'Watchlist',
        setting: 'Settings',
    },
    alert: {
        button: {
            no: 'No',
            yes: 'Yes',
        },
        addSuccess: 'Add success!',
        updateSuccess: 'Update success',
        warning: 'Warning',
    },
    loginScreen: {
        buttonLogin: 'Login',
        labelEmail: 'Email',
        labelPassword: 'Password',
        forgotPassword: 'Forgot password?',
        dontHaveAnAccount: 'You do not have an account? ',
        register: 'Register',
    },
    registerScreen: {
        title: 'Register',
        username: 'Username',
        phone: 'Phone',
        email: 'Email',
        password: 'Password',
        confirm_password: 'Confirm password',
        placeholder_username: 'Tuan Pham Ngoc',
        haveAnAccount: 'Do you have an account? ',
        login: 'Login',
    },
    validateMessage: {
        nameRequired: 'Username is required!',
        signIn: 'Password is incorrect!',
        infoInvalid: 'Info invalid!',
        notCompleted: 'You have not entered the information.',
        emailNotRegister: 'Please enter your email!',
        validatePassword: 'At least 6 character of password!',
        minLength: 'At least 6 character of password!',
        emailInvalid: 'Email is not in the correct format!',
        passwordLength: 'At least 6 character of password!',
        confirmPasswordLength: 'The password and confirmation password do not match.',
        passwordNotMatch: 'The password and confirmation password do not match.',
        emailEmpty: 'Please enter your email!',
        messageLength: 'Do not enter more than 1000 characters.',
        success: 'Register success!',
        titleRequired: 'Title is required!',
        contentRequired: 'Content is required!',
        phoneInvalid: 'Phone invalid',
        require: 'Please enter the information',
        notMatchPassword: 'The password and confirmation password do not match.',
    },
    sendOTPMessage: {
        success: 'A new verification code has been sent.',
        invalidOTP: 'The authorization code is incorrect.',
    },
    input: {
        errorComponent: 'You need wrap input by Form Provider or passing "form = useForm( ... )" into input component',
    },
    settings: {
        logout: 'Logout',
        profile: 'Update Profile',
        english: 'English',
        changeLang: 'Change language',
        selectLang: 'Language selection',
        multiLangSupported: 'Multi language supported',
        vietnamese: 'Vietnamese',
        deleteAccount: 'Delete account',
        delete: 'Confirm',
        deleteConfirm: 'Do you want to delete your account?',
    },
    updateProfile: {
        update: 'Update',
        reset: 'Reset',
    },
};
