export default {
    common: {
        defaultLanguage: 'English',
        close: 'Đóng',
        noText: 'Không có',
        noData: 'Không có dữ liệu',
        cancel: 'Huỷ bỏ',
        confirm: 'Xác nhận',
        haveAnAcc: 'Bạn có tài khoản? ',
        login: 'Đăng Nhập',
        stockMarket: 'Stock Market',
    },
    firstScreen: {
        brand: 'STOCK MARKET',
        description: 'Trải nghiệm mới mẻ \n cùng với sản phẩm của chúng tôi',
        gettingStarted: 'Bắt đầu',
    },
    modalInput: {
        title: 'Xin chào',
        close: 'Đóng',
        button: 'displayModal1',
    },
    tab: {
        home: 'Trang chủ',
        news: 'Bảng tin',
        market: 'Thị trường',
        setting: 'Cài đặt',
    },
    alert: {
        button: {
            no: 'Không',
            yes: 'Có',
        },
        addSuccess: 'Thêm thành công!',
        updateSuccess: 'Cập nhật thành công',
        warning: 'Cảnh báo!',
        complete: 'テストを完了してもよろしいですか？',
        score: '点数',
    },
    noData: {
        noDataList: 'Không có dữ liệu',
        noDataRateList: '評価がまだありません',
        noDataHoliday: 'なし',
    },
    loginScreen: {
        buttonLogin: 'Đăng nhập',
        labelEmail: 'Email',
        labelPassword: 'Mật khẩu',
        forgotPassword: 'Quên mật khẩu?',
        dontHaveAnAccount: 'Bạn không có tài khoản? ',
        register: 'Đăng ký',
    },
    registerScreen: {
        title: 'Đăng ký',
        username: 'Tên đăng nhập',
        phone: 'Số điện thoại',
        email: 'Email',
        password: 'Mật khẩu',
        confirm_password: 'Xác nhận mật khẩu',
        placeholder_username: 'Tuan Pham Ngoc',
        haveAnAccount: 'Bạn đã có tài khoản? ',
        login: 'Đăng nhập',
    },
    validateMessage: {
        nameRequired: 'Tên đăng nhập là bắt buộc!',
        signIn: 'Mật khẩu không chính xác!',
        infoInvalid: 'Thông tin sai!',
        notCompleted: 'Xin hãy điền tất cả!',
        emailNotRegister: 'Địa chỉ email chưa được đăng ký!',
        validatePassword: 'Mật khẩu phải có ít nhất 6 ký tự!',
        emailInvalid: 'Địa chỉ email sai.',
        passwordLength: 'Mật khẩu phải có ít nhất 6 ký tự!',
        confirmPasswordLength: 'Mật khẩu xác nhận sai!',
        passwordNotMatch: 'Mật khẩu xác nhận chưa trùng khớp.',
        emailEmpty: 'Không được để trống email.',
        notMatchPassword: 'Mật khẩu không trùng khớp',
        messageLength: 'Hãy soạn thảo từ 30 ký tự trở lên!',
        success: 'Đăng ký thành công!',
        titleRequired: 'Tiêu đề là bắt buộc!',
        contentRequired: 'Nội dung là bắt buộc',
        minLength: 'Mật khẩu phải có ít nhất 6 ký tự!',
        phoneInvalid: 'Số điện thoại không khả dụng',
        require: 'Xin vui lòng nhập thông tin.',
    },
    sendOTPMessage: {
        success: 'Tôi đã gửi cho bạn một mã mới',
        invalidOTP: 'Mã bạn nhập không chính xác',
    },
    homeListScreen: {
        title: 'メッセージ',
        tab1: '全て',
        tab2: '未読',
        tab3: '既読',
    },
    testScreen: {
        loadingTest: '読み込み中...',
        notification: 'スタートボタンをクリックしてテストを受けてください！',
        startButton: 'Start',
        exercise: '問題 ',
        titleHeader: 'Vocabulary - Kanji - Grammar',
        completeButton: 'Complete',
        topic: '言語知識 (文字 - 単語 - 文法)',
        exercise1: '問題１　＿＿＿のことばの読み方として最もよいものを、１・２・３・４から一つえらびなさい。',
    },
    homeScreen: {
        model: 'モデル',
        detailScreen: '詳細画面',
        dataScreen: 'データ画面',
        userListScreen: 'メッセージ管理画面',
        triggerLoading: '読み込み中',
        testScreen: '試験を受ける',
        batteryScreen: '電池画面',
        quickTest: '速いテストを受ける',
    },
    accountView: {
        name: 'name',
        phone: 'phone',
        email: 'email',
        password: 'password',
        confirmPassword: 'confirmPassword',
    },
    sendOTP: {
        title: 'Mã xác nhận',
        titleForgotPassword: 'Quên mật khẩu',
        sendForgotPassword: 'Xác nhận',
        backButton: 'Trở về',
        descriptionNext:
            '入力したメールアドレスに通知メールを送信しました。\n 認証コードを入力し、「次へ」ボタンを押してください。有効期限は24時間です。',
        descriptionConfirm:
            '入力したメールアドレスに通知メールを送信しました。\n 認証コードを入力し、「確認」ボタンを押してください。有効期限は24時間です。',
        description:
            '入力したメールアドレスに通知メールを送信しました。認証コードを入力し、「登録」ボタンを押してください。有効期限は24時間です。',
        resend: '再送信',
        buttonSend: '登録',
        buttonNext: '次へ',
    },
    errorMessage: {
        emailExisted: 'Địa chỉ email đã tồn tại',
    },
    sendEmail: {
        title: 'Quên mật khẩu',
        sendButtonTitle: 'Tiếp theo',
    },
    picker: {
        pickItem: 'Vui lòng chọn thư mục',
    },
    input: {
        errorComponent: 'You need wrap input by Form Provider or passing "form = useForm( ... )" into input component',
    },
    addMessengerScreen: {
        buttonAdd: 'Add messenger',
        labelTitle: 'Title',
        labelContent: 'Content',
        placeholderTitle: 'your title',
        placeholderContent: 'your content',
    },
    updateMessengerScreen: {
        buttonUpdate: 'Update',
        labelTitle: 'Title',
        labelContent: 'Content',
        labelStatus: 'Status',
    },
    quickTest: {
        complete: '終わる',
        next: '次へ',
        prev: '前へ',
    },
    settings: {
        logout: 'Đăng xuất',
        profile: 'Cập nhật tài khoản',
        english: 'Tiếng Anh',
        vietnamese: 'Tiếng Việt',
        changeLang: 'Thay đổi ngôn ngữ',
        selectLang: 'Lựa chọn ngôn ngữ',
        multiLangSupported: 'Được hỗ trợ tiếng anh và tiếng việt.',
        delete: 'Xác nhận',
        deleteAccount: 'Xoá tài khoản',
        deleteConfirm: 'Bạn muốn xoá tài khoản?',
    },
    updateProfile: {
        update: 'Cập nhật',
        reset: 'Huỷ thay đổi',
    },
};
