export default {
    common: {
        defaultLanguage: 'English',
        close: 'Đóng',
        noText: 'Không có',
        noData: 'Không có dữ liệu',
        cancel: 'Huỷ bỏ',
        confirm: 'Xác nhận',
        haveAnAcc: 'Bạn có tài khoản? ',
        login: 'Đăng Nhập',
        stockMarket: 'Stock Market',
        open: 'Giá mở phiên',
        high: 'Giá cao nhất',
        low: 'Giá thấp nhất',
        closeStock: 'Giá đóng phiên',
        volume: 'Số giao dịch',
        date: 'Ngày',
        symbol: 'Mã chứng khoán',
        search: 'Tìm kiếm',
        notFound: 'Không tìm thấy!',
        ok: 'Đồng ý',
    },
    stock: {
        highestVolume: 'Top giao dịch nhiều nhất trong ngày',
        stockToday: 'Thị trường chứng khoán hôm nay',
    },
    news: {
        comment: 'Bình luận',
        addNews: 'Viết điều gì đó...',
    },
    watchlist: {
        noData: 'Bạn chưa thêm mã nào trong danh sách theo dõi',
        title: 'Danh sách theo dõi',
    },
    confirmModal: {
        addToWatchlist: 'Thêm vào danh sách theo dõi',
        contentTextAdd: 'Dễ dàng theo dõi mã chứng khoán mà bạn quan tâm',
        remove: 'Xoá khỏi danh sách theo dõi',
    },
    firstScreen: {
        brand: 'STOCK MARKET',
        description: 'Trải nghiệm mới mẻ \n cùng với sản phẩm của chúng tôi',
        gettingStarted: 'Bắt đầu',
    },
    modalInput: {
        title: 'Xin chào',
        close: 'Đóng',
        button: 'displayModal1',
    },
    tab: {
        home: 'Trang chủ',
        news: 'Bảng tin',
        market: 'Thị trường',
        setting: 'Cài đặt',
    },
    alert: {
        button: {
            no: 'Không',
            yes: 'Có',
        },
        addSuccess: 'Thêm thành công!',
        updateSuccess: 'Cập nhật thành công',
        warning: 'Cảnh báo!',
    },
    noData: {
        noDataList: 'Không có dữ liệu',
    },
    loginScreen: {
        buttonLogin: 'Đăng nhập',
        labelEmail: 'Email',
        labelPassword: 'Mật khẩu',
        forgotPassword: 'Quên mật khẩu?',
        dontHaveAnAccount: 'Bạn không có tài khoản? ',
        register: 'Đăng ký',
    },
    registerScreen: {
        title: 'Đăng ký',
        username: 'Tên đăng nhập',
        phone: 'Số điện thoại',
        email: 'Email',
        password: 'Mật khẩu',
        confirm_password: 'Xác nhận mật khẩu',
        placeholder_username: 'Tuan Pham Ngoc',
        haveAnAccount: 'Bạn đã có tài khoản? ',
        login: 'Đăng nhập',
    },
    validateMessage: {
        nameRequired: 'Tên đăng nhập là bắt buộc!',
        signIn: 'Mật khẩu không chính xác!',
        infoInvalid: 'Thông tin sai!',
        notCompleted: 'Xin hãy điền tất cả!',
        emailNotRegister: 'Địa chỉ email chưa được đăng ký!',
        validatePassword: 'Mật khẩu phải có ít nhất 6 ký tự!',
        emailInvalid: 'Địa chỉ email sai.',
        passwordLength: 'Mật khẩu phải có ít nhất 6 ký tự!',
        confirmPasswordLength: 'Mật khẩu xác nhận sai!',
        passwordNotMatch: 'Mật khẩu xác nhận chưa trùng khớp.',
        emailEmpty: 'Không được để trống email.',
        notMatchPassword: 'Mật khẩu không trùng khớp',
        messageLength: 'Hãy soạn thảo từ 30 ký tự trở lên!',
        success: 'Đăng ký thành công!',
        titleRequired: 'Tiêu đề là bắt buộc!',
        contentRequired: 'Nội dung là bắt buộc',
        minLength: 'Mật khẩu phải có ít nhất 6 ký tự!',
        phoneInvalid: 'Số điện thoại không khả dụng',
        require: 'Xin vui lòng nhập thông tin.',
    },
    sendOTPMessage: {
        success: 'Tôi đã gửi cho bạn một mã mới',
        invalidOTP: 'Mã bạn nhập không chính xác',
    },
    input: {
        errorComponent: 'You need wrap input by Form Provider or passing "form = useForm( ... )" into input component',
    },
    settings: {
        logout: 'Đăng xuất',
        profile: 'Cập nhật tài khoản',
        english: 'Tiếng Anh',
        vietnamese: 'Tiếng Việt',
        changeLang: 'Thay đổi ngôn ngữ',
        selectLang: 'Lựa chọn ngôn ngữ',
        multiLangSupported: 'Được hỗ trợ tiếng anh và tiếng việt.',
        delete: 'Xác nhận',
        deleteAccount: 'Xoá tài khoản',
        deleteConfirm: 'Bạn muốn xoá tài khoản?',
    },
    updateProfile: {
        update: 'Cập nhật',
        reset: 'Huỷ thay đổi',
    },
};
